In [2]:
import tensorflow as tf

In [2]:
with tf.name_scope("my_scope"):
    v1 = tf.get_variable("var1", [1], dtype=tf.float32)
    v2 = tf.Variable(1, name="var2", dtype=tf.float32)
    a = tf.add(v1, v2)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [3]:
print(v1.name)
print(v2.name)
print(a.name)

var1:0
my_scope/var2:0
my_scope/Add:0


In [5]:
with tf.variable_scope("my_scoped"):
    v1 = tf.get_variable("var1", [1], dtype=tf.float32)
    v2 = tf.Variable(1, name="var2", dtype=tf.float32)
    v3 = tf.Variable(1, name="var2", dtype=tf.float32)
    a = tf.add(v1, v3)

print(v1.name)  # my_scope/var1:0
print(v2.name)  # my_scope/var2:0
print(a.name) 

my_scoped/var1:0
my_scoped/var2:0
my_scoped/Add:0


In [6]:
print(v3.name)

my_scoped/var2_1:0


In [7]:
my_var= tf.Variable(4, name="my_variable")

In [8]:
add= tf.add(3, my_var)

In [9]:
print(add)

Tensor("Add:0", shape=(), dtype=int32)


In [10]:
sess= tf.Session()
sess.run(my_var.initializer)
print(my_var.eval(session=sess))

4


In [11]:
#sess.run(.initializer)
print(add.eval(session=sess))

7


In [12]:
zeros= tf.zeros([3,3])

In [15]:
print(zeros.eval(session=sess))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
print(sess.run(zeros))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
uniform= tf.random.uniform([3,3], minval=0 , maxval =5)

In [18]:
print(sess.run(uniform))

[[1.5243053  2.0037956  0.7506585 ]
 [1.1200643  2.7734714  3.8732672 ]
 [1.0103953  2.2070246  0.11396468]]


In [3]:
with tf.variable_scope("foo"):
    v= tf.get_variable("v", [1])
assert v.name == "foo/v:0"

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
assert v.name == "foo/v:0"