In [2]:
import tensorflow as tf

In [3]:
count = tf.get_variable("count", shape=(), initializer=tf.constant_initializer(1), trainable=False)
count_increment = tf.assign_add(count, 1)
c = tf.constant(2.)
with tf.control_dependencies([count_increment]):
    d = c + 3
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("eval count", count.eval())
    print("eval d", d.eval())
    print("eval count", count.eval())

eval count 1.0
eval d 5.0
eval count 2.0


In [4]:
import tensorflow as tf
with tf.variable_scope('layer1', reuse=tf.AUTO_REUSE):
    w1 = tf.Variable(tf.random_normal(shape=[2,2], mean=0, stddev=1), name='w')
    w2 = tf.get_variable(name = 'w',initializer = tf.random_normal(shape=[3,3], mean=0, stddev=1))

In [5]:
with tf.Session() as sess:  
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    
    print("w1 = ")
    print(w1.name)
    print(w1.eval())
    print("w2 = ")
    print(w2.name)
    print(w2.eval())

w1 = 
layer1/w:0
[[-0.38807675 -0.6655896 ]
 [ 0.02820808  1.3654466 ]]
w2 = 
layer1/w_1:0
[[ 0.11230986  0.71307886  1.4159217 ]
 [-1.0980045  -3.5468857  -1.8328775 ]
 [-0.31819475 -0.42424977  0.73017216]]


In [7]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [8]:
import tensorflow as tf
with tf.variable_scope('layer1', reuse= None):
    w1 = tf.get_variable(name = 'w',initializer = tf.random_normal(shape=[3,3], mean=0, stddev=1))
    w2 = tf.get_variable(name = 'w',initializer = tf.random_normal(shape=[3,3], mean=0, stddev=1))

ValueError: Variable layer1/w already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Users\rajim\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\Users\rajim\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\rajim\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\rajim\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\rajim\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 2023, in variable_v2
    shared_name=shared_name, name=name)


In [9]:
import tensorflow as tf
with tf.variable_scope('layer1', reuse= tf.AUTO_REUSE):
    with tf.variable_scope('layer_sub_1', reuse = None):
        w1 = tf.get_variable(name = 'w',initializer = tf.random_normal(shape=[3,3], mean=0, stddev=1))
        w2 = tf.get_variable(name = 'w',initializer = tf.random_normal(shape=[3,3], mean=0, stddev=1))

In [10]:
with tf.Session() as sess:  
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    
    print("w1 = ")
    print(w1.name)
    print(w1.eval())
    print("w2 = ")
    print(w2.name)
    print(w2.eval())

w1 = 
layer1/layer_sub_1/w:0
[[-0.251052   -1.8924432   1.353009  ]
 [-0.18623108 -0.21473028  0.12503529]
 [ 0.88305956 -0.10542694 -2.9023087 ]]
w2 = 
layer1/layer_sub_1/w:0
[[-0.251052   -1.8924432   1.353009  ]
 [-0.18623108 -0.21473028  0.12503529]
 [ 0.88305956 -0.10542694 -2.9023087 ]]


In [13]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [15]:
import tensorflow as tf
with tf.variable_scope('layer1', reuse= True):
    w1 = tf.get_variable(name = 'w',initializer = tf.random_normal(shape=[3,3], mean=0, stddev=1))
    w2 = tf.get_variable(name = 'w',initializer = tf.random_normal(shape=[3,3], mean=0, stddev=1))

In [16]:
with tf.Session() as sess:  
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    
    print("w1 = ")
    print(w1.name)
    print(w1.eval())
    print("w2 = ")
    print(w2.name)
    print(w2.eval())

w1 = 
layer1/w_1:0
[[-1.3622909   0.14102133 -0.20322452]
 [-0.20735505 -0.62965536 -0.42845145]
 [ 0.33738825 -0.11997794  0.60588163]]
w2 = 
layer1/w_1:0
[[-1.3622909   0.14102133 -0.20322452]
 [-0.20735505 -0.62965536 -0.42845145]
 [ 0.33738825 -0.11997794  0.60588163]]
