In [3]:
import tensorflow as tf
from keras.layers import Conv2D, ZeroPadding2D, Activation, Input, concatenate
import numpy as np

In [26]:
import tensorflow.keras.backend as K

In [4]:
input_shape = (1, 1, 2, 2)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
print(x)

[[[[0 1]
   [2 3]]]]


In [12]:
np.arange(np.prod(input_shape)).reshape(input_shape).shape

(1, 1, 2, 2)

In [10]:
np.arange(np.prod((2,2,3,4)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [14]:
y = tf.keras.layers.ZeroPadding2D(padding=1)(x)

In [15]:
print(y)

Tensor("zero_padding2d_1/Pad:0", shape=(1, 3, 4, 2), dtype=int32)


In [17]:
np(1,2,1,2).reshape(2,2)

TypeError: 'module' object is not callable

In [31]:
z= np.array([1,1,2,2])

In [32]:
z= z.reshape(1,1,2,2)

In [33]:
z

array([[[[1, 1],
         [2, 2]]]])

In [34]:
zeroPad1 = ZeroPadding2D((1,1), name='zeroPad1', dim_ordering='th')

C:\Users\rajim\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `ZeroPadding2D` call to the Keras 2 API: `ZeroPadding2D((1, 1), name="zeroPad1", data_format="channels_first")`
  """Entry point for launching an IPython kernel.


In [35]:
z=K.constant(z)

In [36]:
zeroPad1(z)

<tf.Tensor 'zeroPad1_2/Pad:0' shape=(1, 1, 4, 4) dtype=float32>

In [37]:
ZeroPadding2D(5)(z)

<tf.Tensor 'zero_padding2d_2/Pad:0' shape=(1, 11, 12, 2) dtype=float32>

In [38]:
print(ZeroPadding2D(5)(z))

Tensor("zero_padding2d_3/Pad:0", shape=(1, 11, 12, 2), dtype=float32)


In [42]:
with tf.Session() as sess:  
    print(zeroPad1(z).eval()) 

[[[[0. 0. 0. 0.]
   [0. 1. 1. 0.]
   [0. 2. 2. 0.]
   [0. 0. 0. 0.]]]]


In [49]:
with tf.Session() as sess:
    print(ZeroPadding2D(padding=((1,1),(1,1)))(z).eval())

[[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [1. 1.]
   [2. 2.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]]
