In [2]:
import tensorflow as tf
import numpy as np
#tf.compat.v1.reset_default_graph()

In [7]:
# After eager execution is enabled, operations are executed as they are
# defined and Tensor objects hold concrete values, which can be accessed as
# numpy.ndarray`s through the numpy() method.
#ensure to run this either at the start of the coding or after restarting the kernel
tf.compat.v1.enable_eager_execution()           #enabled
print(tf.multiply(6, 7).numpy())

tf.compat.v1.disable_eager_execution()       #disabled

42


In [ ]:
####variable_and_constants_declarations
 
#name_scope      name scope is ignored by tf.get_variable.
# get_variable
# Variable
# variable_scope
# random.uniform([3,3], minval=0 , maxval =5)
# zeros([3,3])
# constant
#initialize_all_variables


In [3]:
with tf.name_scope("my_scope"):
    v1 = tf.get_variable("var1", [1], dtype=tf.float32)
    v2 = tf.Variable(1, name="var1", dtype=tf.float32)
    a = tf.add(v1, v2)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [4]:
print(v1.name)
print(v2.name)
#print(a.name)

var1:0
my_scope/var1:0


In [5]:
with tf.variable_scope("my_scoped"):
    v1 = tf.get_variable("var1", [1], dtype=tf.float32)
    v2 = tf.Variable(1, name="var2", dtype=tf.float32)
    v3 = tf.Variable(1, name="var2", dtype=tf.float32)
    a = tf.add(v1, v3)

print(v1.name)  # my_scope/var1:0
print(v2.name) # my_scope/var2:0
print(v3.name)
print(a.name) 

my_scoped/var1:0
my_scoped/var2:0
my_scoped/Add:0


In [7]:
my_var= tf.Variable(4, name="my_variable")

In [8]:
add= tf.add(3, my_var)

In [9]:
print(add)

Tensor("Add:0", shape=(), dtype=int32)


In [10]:
sess= tf.Session()
sess.run(my_var.initializer)
print(my_var.eval(session=sess))

4


In [11]:
#sess.run(.initializer)
print(add.eval(session=sess))

7


In [12]:
zeros= tf.zeros([3,3])

In [15]:
print(zeros.eval(session=sess))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
print(sess.run(zeros))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
#uniform= tf.random.uniform([3,3], minval=0 , maxval =5)


In [18]:
print(sess.run(uniform))

[[1.5243053  2.0037956  0.7506585 ]
 [1.1200643  2.7734714  3.8732672 ]
 [1.0103953  2.2070246  0.11396468]]


In [3]:
with tf.variable_scope("foo"):
    v= tf.get_variable("v", [1])
assert v.name == "foo/v:0"

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
assert v.name == "foo/v:0"

In [50]:
sess= tf.Session()
ok = tf.pow(8.0, 1/3, name = "bode2") 
print(sess.run(ok))

2.0


In [68]:
sess= tf.Session()
uniform= tf.random.uniform([10,3], minval=1 , maxval =5, dtype=tf.int32)
uniform1 = tf.reduce_mean(uniform)
#print(sess.run(uniform))
#rows = tf.gather(temp_var, idx)
#print(sess.run(tf.gather(uniform, tf.constant([0, 2]))))
uniform= tf.random.uniform([10,3], minval=1 , maxval =5, dtype=tf.int32)
with tf.Session() as sess:
    uniform= uniform.eval()
    print(uniform)
    print(uniform[0:2])
    

[[1 3 4]
 [2 1 2]
 [4 3 3]
 [2 3 2]
 [3 3 1]
 [1 4 4]
 [3 3 4]
 [3 1 3]
 [2 3 4]
 [4 4 2]]
[[1 3 4]
 [2 1 2]]


In [47]:
1+1+4+4+4+4

18

In [ ]:
#####feed_dicting and place_holding 


#feed_dict= {input_a: uniform1}
#tf.placeholder(tf.float32, [None, 3])

In [41]:
input_a = tf.placeholder(tf.float32, [None, 3])
for i in range(4):
    with tf.Session() as sess:
        uniform1= tf.random.uniform([1,3], minval=0 , maxval =5)
        #feed_dict doesnt accept tf tensor
        uniform1 = uniform1.eval()
        bode1 = tf.constant(3.0)
        bode = tf.multiply(input_a,bode1)
        aonat = sess.run(bode, feed_dict= {input_a: uniform1})
        print(aonat)
        print(bode1.name)    

[[ 2.8618276 12.32141    1.316387 ]]
Const_1:0
[[4.495987  2.4400754 5.196615 ]]
Const_2:0
[[8.906898  8.02437   5.9316483]]
Const_3:0
[[ 0.20780325 10.652547    2.7350092 ]]
Const_4:0


In [ ]:
#####operations


# between each epoch and the next the variables with number appended is created may be by tf.Variable()


# tf.add(a, b)
# tf.substract(a, b)
# tf.multiply(a, b)
# tf.div(a, b)
# tf.pow(a, b)
# tf.exp(a)
# tf.sqrt(a)
#tf.matmul

In [ ]:
#######
# softmax
# sigmoid
# relu
# logit
# tf.nn.softmax(logits, name=None)

# tf.nn.softmax_cross_entropy_with_logits(logits, labels, name=None)  logit just means 
# the input is not probability so dont think a logit function is done on the input at all

# tf.sparse.nn.softmax_cross_entropy_with_logits

# if you use categorical-cross-entropy you need one-hot encoding, and if you use 
# sparse-categorical-cross-entropy you encode as normal integers.

# cross-entropy
# binary-cross-entropy == at each point it is either a or others(b + c)
# categorical-crossentropy == at each point it is just a or b or c

In [ ]:
#define 

In [129]:
tf.compat.v1.reset_default_graph()
x = tf.random.uniform([10,3], minval=0 , maxval =5)
y = tf.random.uniform([10,1], minval=0 , maxval =1)
n = tf.placeholder(tf.float32, [1])
y_pred = tf.placeholder(tf.float32, [1])
y_true = tf.placeholder(tf.float32, [1])
def custom_cost(y_pred, y_true):
    cost = tf.pow(tf.pow(tf.subtract(y_pred,y_true), 4.0), 1/4.0)
    #cost = tf.constant(5.0)
    return cost
    
input_a = tf.placeholder(tf.float32, [None, 3])
#wx+b
def neural_net(input_a):
    
    weight = tf.Variable(tf.random_normal([3, 3]))
    bias = tf.Variable(tf.random_normal([3]))

    weight_b = tf.Variable(tf.random_normal([3, 1]))
    bias_b = tf.Variable(tf.random_normal([1]))



    layer1 = tf.add(tf.matmul(input_a, weight), bias)
    layer2 = tf.add(tf.matmul(layer1, weight_b), bias_b)
    
    return layer2
pred = neural_net(input_a)
cost = custom_cost(pred, y_true)
#ok = neural_net(x_np[0:2])
#ok = neural_net(x)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    x_np = x.eval()
    y_np = y.eval()
    for i in range(5):
        
        neural_net_res, cost_val = sess.run([pred, cost], feed_dict = {input_a: x_np[i].reshape(1,3), y_true: y_np[i]}
                                 )
        print(neural_net_res)
        print(y_np[i])
        print(cost_val)
        
        #print(ok)
        #ok.eval()

[[4.253005]]
[0.4732299]
[[3.7797751]]
[[6.245085]]
[0.16763043]
[[6.0774546]]
[[5.6833262]]
[0.6523453]
[[5.030981]]
[[1.2022153]]
[0.44228375]
[[0.75993156]]
[[7.519516]]
[0.28818727]
[[7.231329]]


In [99]:
x = tf.random.uniform([10,3], minval=0 , maxval =5)


with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    for i in range(1):
        x_np = x.eval()
        print(x_np[0])
        print(x_np[0].reshape(1,3))
        #print(x_np[0])
        #print(x_np[0].shape)
        

[4.4608984 4.08389   4.8499727]
[[4.4608984 4.08389   4.8499727]]


In [ ]:
#####saving and restoring tensorflow sessions:
##ensure to restore all you need to run your sess.run() 

In [14]:
import tensorflow as tf
tf.compat.v1.reset_default_graph()

#Prepare to feed input, i.e. feed_dict and placeholders
w1 = tf.placeholder("float", name="w1")
w2 = tf.placeholder("float", name="w2")
b1= tf.Variable(2.0,name="bias")
b2= tf.Variable(3.0,name="bias1")
feed_dict ={w1:4,w2:8}

#Define a test operation that we will restore
w3 = tf.add(w1,w2)
w4 = tf.multiply(w3,b1,name="op_to_restore")
w5 = tf.multiply(w4,b2,name="op_to_restore1")
sess = tf.Session()
sess.run(tf.global_variables_initializer())

#Create a saver object which will save all the variables
saver = tf.train.Saver()

#Run the operation by feeding input
print(sess.run(w5,feed_dict))
#Prints 24 which is sum of (w1+w2)*b1 

#Now, save the graph
saver.save(sess, 'my_test_model',global_step=1000)

72.0


'my_test_model-1000'

In [16]:

import tensorflow as tf
tf.compat.v1.reset_default_graph()
sess=tf.Session()    
#First let's load meta graph and restore weights
saver = tf.train.import_meta_graph('my_test_model-1000.meta')
saver.restore(sess,tf.train.latest_checkpoint('./'))


# Access saved Variables directly
print(sess.run('bias1:0'))
# This will print 2, which is the value of bias that we saved


# Now, let's access and create placeholders variables and
# create feed-dict to feed new data

graph = tf.get_default_graph()
w1 = graph.get_tensor_by_name("w1:0")
w2 = graph.get_tensor_by_name("w2:0")
feed_dict ={w1:13.0,w2:17.0}

#Now, access the op that you want to run. 
op_to_restore1 = graph.get_tensor_by_name("op_to_restore1:0")

#graph = tf.get_default_graph()
with sess.as_default(), sess.graph.as_default():
    loaded_vars = tf.trainable_variables()
    for j in loaded_vars:
        print(j)
all_ops = tf.get_default_graph().get_operations()
#for kk in all_ops:
#    print(kk.name)
#print(all_ops[1].name)
all_nodes = [n for n in tf.get_default_graph().as_graph_def().node]
for kk in all_nodes:
    print(kk.name)

#print(sess.run(op_to_restore1,feed_dict))
#This will print 60 which is calculated 

INFO:tensorflow:Restoring parameters from ./my_test_model-1000
3.0
<tf.Variable 'bias:0' shape=() dtype=float32_ref>
<tf.Variable 'bias1:0' shape=() dtype=float32_ref>
w1
w2
bias/initial_value
bias
bias/Assign
bias/read
bias1/initial_value
bias1
bias1/Assign
bias1/read
Add
op_to_restore
op_to_restore1
init
save/filename/input
save/filename
save/Const
save/SaveV2/tensor_names
save/SaveV2/shape_and_slices
save/SaveV2
save/control_dependency
save/RestoreV2/tensor_names
save/RestoreV2/shape_and_slices
save/RestoreV2
save/Assign
save/Assign_1
save/restore_all
